### ISSUE TITLE
Read CPU Count

### ISSUE THREAD

**Issue by elJoeyJojo** [GoogleCloudPlatform/terraform-google-alloy-db#11]
I was trying to pass in a variable to control CPU count on read instance but doesn't work. It appears the resource doesn't take in a  _machine_cpu_count_ like the _primary_ resource

```
resource "google_alloydb_instance" "read_pool" {
  for_each      = local.read_pool_instance
  cluster       = google_alloydb_cluster.default.name
  instance_id   = each.key
  instance_type = each.value.instance_type

  read_pool_config {
    node_count = each.value.node_count
  }

  database_flags = each.value.database_flags

  depends_on = [google_alloydb_instance.primary]
}
```

**Comment by elJoeyJojo** [comment]
is this module going to be tagged? it still shows as 0.1.0 https://registry.terraform.io/modules/GoogleCloudPlatform/alloy-db/google/latest

**Comment by imrannayer** [comment]
@elJoeyJojo you can either wait for 0.2 release or you can directly point to github main branch to get the feature.

**Comment by elJoeyJojo** [comment]
thanks @imrannayer
