### ISSUE TITLE
Support for creating Basic (Zonal) Instances

### ISSUE THREAD

**Issue by jdub55** [GoogleCloudPlatform/terraform-google-alloy-db#33]
It looks like creation of a basic (zonal) AlloyDB instance is now GA (https://cloud.google.com/alloydb/docs/basic-instance#gcloud) 

Can we add Terraform Support for creating this type of AlloyDB instance?

**Comment by imrannayer** [comment]
@jdub55 apparently module was written in a way that it was always possible to provide primary instance zone and availability type. You can pass [gce_zone](https://github.com/GoogleCloudPlatform/terraform-google-alloy-db/blob/190a63181431d4b069a721a24c8a185033b8ccc6/variables.tf#L113C7-L113C7) and [availability_type](https://github.com/GoogleCloudPlatform/terraform-google-alloy-db/blob/190a63181431d4b069a721a24c8a185033b8ccc6/variables.tf#L114C5-L114C22) in variable [primary_instance](https://github.com/GoogleCloudPlatform/terraform-google-alloy-db/blob/190a63181431d4b069a721a24c8a185033b8ccc6/variables.tf#L105). 

Go ahead and try.
