### ISSUE TITLE
When will this be published?

### ISSUE THREAD

**Issue by elJoeyJojo** [GoogleCloudPlatform/terraform-google-alloy-db#8]
Not an issue but a question. I would like to start using this module but I don't see it published in Terraform Modules.
Thanks

**Comment by imrannayer** [comment]
@apeabody @anaik91

**Comment by apeabody** [comment]
Hi @bharathkkb - Can you recommend someone?

**Comment by elJoeyJojo** [comment]
I mean I know how to use this but i don't wanna have to clone this repo and reference it locally, I wanna use the github source if that makes any sense

**Comment by g-awmalik** [comment]
[v0.1.0](https://github.com/GoogleCloudPlatform/terraform-google-alloy-db/tree/v0.1.0) is published.
