### ISSUE TITLE
Enable network_config and authorized_external_networks blocks configurations in google_alloydb_instance

### ISSUE THREAD

**Issue by bruno561** [GoogleCloudPlatform/terraform-google-alloy-db#81]
Please enable `network_config` and `authorized_external_networks` blocks with their respective variables in `google_alloydb_instance`.

More information: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_instance#nested_network_config

Ty.

**Comment by imrannayer** [comment]
fixed in #82
